#!/bin/sh

# udev rule creates symbolic link below
DEVNODE=/dev/video-logi-c920

/usr/bin/v4l2-ctl -d ${DEVNODE} \
    --set-fmt-video=pixelformat=MJPG,width=1280,height=720 \
    --set-ctrl brightness=250 \
    --set-ctrl contrast=190 \
    --set-ctrl backlight_compensation=1 \
    --set-ctrl zoom_absolute=130 \
    --set-ctrl tilt_absolute=-18000